name:                stochastic-memoization
version:             0.1.0.0
github:              "githubuser/stochastic-memoization"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stochastic-memoization#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- free
- mtl
- monad-bayes
- diagrams-core
- diagrams-lib
- diagrams-svg
- containers
- data-fix
- comonad
- log-domain

library:
  source-dirs: src

executables:
  stochastic-memoization-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stochastic-memoization

tests:
  stochastic-memoization-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stochastic-memoization
